jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous:    true
            security: true
            

    access_control:
        - { path: ^/ctrlw/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ctrlw/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ctrlw/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ctrlw/*, role: ROLE_USER }       
        - { path: new , role: ROLE_USER }  
        - { path: edit, role: ROLE_USER }  