<?php

namespace Panel\CtrlwBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * clienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clienteRepository extends EntityRepository
{
    public function findBySearch($sStr)
    {
        $em = $this->getEntityManager();
        $sStr = '%'.$sStr.'%';
        return $em->getRepository("PanelCtrlwBundle:Clientes")->createQueryBuilder('c')
                ->where('c.apenom LIKE :apenom')
                ->orWhere('c.cuit LIKE :cuit')
                ->orderBy('c.apenom','DESC')
                ->setParameter('apenom', $sStr)
                ->setParameter('cuit', $sStr)
                ->getQuery()->getResult();
    }
}
