<?php

namespace Panel\NovedadesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * novedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class novedadesRepository extends EntityRepository
{
    public function findBySearch($sStr)
    {
        $em = $this->getEntityManager();
        $sStr = '%'.$sStr.'%';
        return $em->getRepository("PanelNovedadesBundle:Novedades")->createQueryBuilder('c')
                ->where('c.titulo LIKE :titulo')
                ->orWhere('c.cuerpo LIKE :cuerpo')
                ->orderBy('c.titulo','DESC')
                ->setParameter('titulo', $sStr)
                ->setParameter('cuerpo', $sStr)
                ->getQuery()->getResult();
    }
}
