services:
    panel_ctrlw.registration.form.type:
        class: Panel\CtrlwBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mi_user_registration }